/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WishIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WishIn{}

// WishIn struct for WishIn
type WishIn struct {
	Product string `json:"product"`
	Price float32 `json:"price"`
	Url string `json:"url"`
	Priority PriorityEnum `json:"priority"`
}

type _WishIn WishIn

// NewWishIn instantiates a new WishIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWishIn(product string, price float32, url string, priority PriorityEnum) *WishIn {
	this := WishIn{}
	this.Product = product
	this.Price = price
	this.Url = url
	this.Priority = priority
	return &this
}

// NewWishInWithDefaults instantiates a new WishIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWishInWithDefaults() *WishIn {
	this := WishIn{}
	return &this
}

// GetProduct returns the Product field value
func (o *WishIn) GetProduct() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Product
}

// GetProductOk returns a tuple with the Product field value
// and a boolean to check if the value has been set.
func (o *WishIn) GetProductOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Product, true
}

// SetProduct sets field value
func (o *WishIn) SetProduct(v string) {
	o.Product = v
}

// GetPrice returns the Price field value
func (o *WishIn) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *WishIn) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *WishIn) SetPrice(v float32) {
	o.Price = v
}

// GetUrl returns the Url field value
func (o *WishIn) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WishIn) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WishIn) SetUrl(v string) {
	o.Url = v
}

// GetPriority returns the Priority field value
func (o *WishIn) GetPriority() PriorityEnum {
	if o == nil {
		var ret PriorityEnum
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *WishIn) GetPriorityOk() (*PriorityEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *WishIn) SetPriority(v PriorityEnum) {
	o.Priority = v
}

func (o WishIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WishIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product"] = o.Product
	toSerialize["price"] = o.Price
	toSerialize["url"] = o.Url
	toSerialize["priority"] = o.Priority
	return toSerialize, nil
}

func (o *WishIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"product",
		"price",
		"url",
		"priority",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWishIn := _WishIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWishIn)

	if err != nil {
		return err
	}

	*o = WishIn(varWishIn)

	return err
}

type NullableWishIn struct {
	value *WishIn
	isSet bool
}

func (v NullableWishIn) Get() *WishIn {
	return v.value
}

func (v *NullableWishIn) Set(val *WishIn) {
	v.value = val
	v.isSet = true
}

func (v NullableWishIn) IsSet() bool {
	return v.isSet
}

func (v *NullableWishIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWishIn(val *WishIn) *NullableWishIn {
	return &NullableWishIn{value: val, isSet: true}
}

func (v NullableWishIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWishIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


